

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_PASSWORD: ppass
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-config/memory-limit.xml:/etc/clickhouse-server/config.d/memory-limit.xml
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      clickhouse:
        condition: service_healthy

  collector:
    build: .
    depends_on:
      clickhouse:
        condition: service_healthy
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: 5432
      POSTGRES_DB: testdb1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: 3306
      MYSQL_DB: testdb1
      MYSQL_USER: admin
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: 6379

      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ppass

      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}

volumes:
  clickhouse_data:
  grafana_data: