apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
        - name: collector
          image: db-reliability-platform-collector:latest
          imagePullPolicy: Never
          env:
            - name: POSTGRES_HOST
              value: "db-reliability-postgres-tf.cfooacks8hqs.eu-north-1.rds.amazonaws.com"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "testdb1"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: collector-secrets
                  key: POSTGRES_PASSWORD

            - name: MYSQL_HOST
              value: "db-reliability-mysql-tf.cfooacks8hqs.eu-north-1.rds.amazonaws.com"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DB
              value: "testdb1"
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: collector-secrets
                  key: MYSQL_PASSWORD

            - name: REDIS_HOST
              value: "master.db-reliability-redis-tf.hh6frt.eun1.cache.amazonaws.com"
            - name: REDIS_PORT
              value: "6379"

            - name: CLICKHOUSE_HOST
              value: "clickhouse"
            - name: CLICKHOUSE_PORT
              value: "8123"
            - name: CLICKHOUSE_USER
              value: "default"
            - name: CLICKHOUSE_PASSWORD
              value: "ppass"

            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: collector-secrets
                  key: SLACK_WEBHOOK_URL
          resources:
            limits:
              memory: "150Mi"
            requests:
              memory: "80Mi"